name: CI Pipeline

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Display Build Message
        run: echo "Build Success!"

      - name: Notify Slack
        if: success()
        run: |
          curl -X POST \
            -H 'Content-type: application/json' \
            --data '{"text":"Build Completed Successfully!"}' \
            ${{ secrets.SLACK_WEBHOOK_URL }}
